version: "3"

services:

  adminservice:
    build: ./admin-service/
    ports:
      - "3001:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/testmongodata
  vendorservice:
    build: ./vendor-service/
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/testmongodata

  userservice:
    build: ./user-service/

     ports:
      - "3003:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/testmongodata

  itemservice:
    build: ./item-service/

     ports:
      - "3004:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/testmongodata
      
   ordersservice:
    build: ./orders-service/

     ports:
      - "3005:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/testmongodata
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - adminservice
      - vendorservice
      - userservice
      - itemservice
      - ordersservice
